### ISSUE TITLE
TESTI IMMAGINI SLIDER

### ISSUE THREAD

**Issue by pprestifilippo** [domecsolutions/dtweb#12]
PRIMA SLIDE CON COMPUTER E IPHONE (FOTO DI SFONDO CI PENSA VALE)

Frase Grande:COSTRUIAMO I VOSTRI SISTEMI PROMOZIONALI ATTRAVERSO MOBILE E WEB APP DEDICATE
Frase Piccola:UNA PROFONDA CONNESSIONE EMOTIVA CON IL CLIENTE

----------------------------------------------------------------------------------------------------------------------------
SECONDA SLIDE CON INFO GRAFICA FATTA DA VALENTINA

Frase Grande: GUIDIAMO LE AZIENDE NEL MONDO DEL CUSTOMER ENGAGEMENT E DEL PROMOTION MANAGEMENT EVOLUTO

Frase Piccola: PROCESSING DEI SERVIZI A VALORE AGGIUNTO BASATI SU SOLUZIONI SAAS

**Comment by pprestifilippo** [comment]
Le frasi da te caricate sono diverse da quelle da me indicate...non puoi chiedere di fare delle cose e poi decidere cosa mettere...così non valgono tutti i discorsi fatti al telefono...
A me piacciono le frasi così come le avevo pensate

**Comment by domecsolutions** [comment]
Si. Ho ritenuto opportuno togliere alcune cose per coerenza e modificarne altre per ragioni di spazio.
