### ISSUE TITLE
TESTI SEZIONE FEATURES

### ISSUE THREAD

**Issue by pprestifilippo** [domecsolutions/dtweb#13]
La frase "More and more extra great feautres" deve essere sostituita con "Tante grandi funzionalità a portata di mano" e sotto bisogna inserire "Tutto ciò di cui hai bisogno per far crescere il business"

ICONA IN ALTO A SX
REPORTING (sostituire l'attuale icona "fa-bar-chart big-icon pull-right" con "fa-line-chart big-icon pull-right")
Report interattivi per monitorare i principali KPI e guidare il proprio business nella giusta direzione gestendo con semplicità tempistiche e modalità. 

------
ICONA IN ALTO A DX
APP CHECKER (sostituire l'attuale icona a "fa-bolt big-icon pull-right" con "fa-mobile-phone big-icon pull-right" )
Velocità nell'implementazione di Mobile e Web App multipiattaforma per la gestione semplice ed intuitiva delle proprie campagne promozionali.

------
ICONA IN BASSO A SX
ACCELERATORI DI PROMOZIONE (sostituire l'attuale icona "fa-clock-o big-icon pull-right" con "fa-bolt big-icon pull-right" )
Fidelizzare i clienti attraverso l'uso di moltiplicatori di punti, concentrati su prodotti, giorni, orari prestabiliti, totali di spesa e altro ancora.

------
ICONA IN BASSO A DX
CO-MARKETING (l'icona con gli omini non cambia)
Accrescere la visibilità del brand e diffondere il prodotto attraverso l'ultilizzo di mezzi, canali e customer base di parter esterni.

**Comment by domecsolutions** [comment]
Il testo è troppo poco ed il template non viene visualizzato correttamente. Occorre tenere in considerazione di utilizzare lo stesso numero di parole già presenti.
Inoltre occorre specificare anche il terzo titolo (quello che in verde viene indicato dalla scritta INSPINIA)

**Comment by pprestifilippo** [comment]
La frase "More and more extra great feautres" deve essere sostituita con "Tante grandi funzionalità a portata di mano" e sotto bisogna inserire "Tutto ciò di cui hai bisogno per far crescere il business"

ICONA IN ALTO A SX
REPORTING (sostituire l'attuale icona "fa-bar-chart big-icon pull-right" con "fa-line-chart big-icon pull-right")
Report interattivi per monitorare i principali KPI e guidare il proprio business nella giusta direzione gestendo con semplicità tempistiche e modalità. Ti aiutiamo a conoscere i punti di forza e di miglioramento di una campagna per scrivere insieme delle storie di successo.

ICONA IN ALTO A DX
APP CHECKER (sostituire l'attuale icona a "fa-bolt big-icon pull-right" con "fa-mobile-phone big-icon pull-right" )
Velocità nell'implementazione di Mobile e Web App multipiattaforma per la gestione semplice ed intuitiva delle proprie campagne promozionali. App Checker: una mobile app "white label" pronta per sostituire i normali pos e procedere con l'accettazione delle tue carte promozionali.

ICONA IN BASSO A SX
ACCELERATORI DI PROMOZIONE (sostituire l'attuale icona "fa-clock-o big-icon pull-right" con "fa-bolt big-icon pull-right" )
Fidelizzare i clienti attraverso l'uso di moltiplicatori di punti, concentrati su prodotti, giorni, orari prestabiliti, totali di spesa e altro ancora. Strumenti semplici per il cross-selling e l'up-selling dei vostri prodotti. Minimo sforzo e massimo risultato.

ICONA IN BASSO A DX
CO-MARKETING (l'icona con gli omini non cambia)
Accrescere la visibilità del brand e diffondere il prodotto attraverso l'ultilizzo di mezzi, canali e customer base di parter esterni. Aumentate la penetrazione dei vostri prodotti nel mercato attraverso le reti di distribuzione dei nostri clienti partner.

**Comment by pprestifilippo** [comment]
al posto di ISPINIA metterei DOMEC

**Comment by pprestifilippo** [comment]
Ciao Vincenzo,
con Fede abbiamo pensato alle parole mancanti da da aggiungere. Cortesemente inserisci queste 

ICONA IN ALTO A SX
ANALISI(in piccolo)
REPORTING (sostituire l'attuale icona "fa-bar-chart big-icon pull-right" con "fa-line-chart big-icon pull-right")
Report interattivi per monitorare i principali KPI e guidare il proprio business nella giusta direzione gestendo con semplicità tempistiche e modalità. Ti aiutiamo a conoscere i punti di forza e di miglioramento di una campagna per scrivere insieme delle storie di successo.

ICONA IN ALTO A DX
STRUMENTI(in piccolo)
APP CHECKER (sostituire l'attuale icona a "fa-bolt big-icon pull-right" con "fa-mobile-phone big-icon pull-right" )
Velocità nell'implementazione di Mobile e Web App multipiattaforma per la gestione semplice ed intuitiva delle proprie campagne promozionali. App Checker: una mobile app "white label" pronta per sostituire i normali pos e procedere con l'accettazione delle tue carte promozionali.

ICONA IN BASSO A SX
MECCANICHE o STRATEGIA(in piccolo)
ACCELERATORI DI PROMOZIONE (sostituire l'attuale icona "fa-clock-o big-icon pull-right" con "fa-bolt big-icon pull-right" )
Fidelizzare i clienti attraverso l'uso di moltiplicatori di punti, concentrati su prodotti, giorni, orari prestabiliti, totali di spesa e altro ancora. Strumenti semplici per il cross-selling e l'up-selling dei vostri prodotti. Minimo sforzo e massimo risultato.

ICONA IN BASSO A DX
SINERGIA (in piccolo)
CO-MARKETING (l'icona con gli omini non cambia)
Accrescere la visibilità del brand e diffondere il prodotto attraverso l'utilizzo di mezzi, canali e customer base di partner esterni. Aumentate la penetrazione dei vostri prodotti nel mercato attraverso le reti di distribuzione dei nostri clienti partner.

**Comment by domecsolutions** [comment]
La issue è stata risolta come indicato
